### PR TITLE
Implemented RESAMPLE EVERY and RESAMPLE FOR for Continuous Queries.

### PR DESCRIPTION
**Pull request by DJFliX**

### CODE REVIEW

**Comment by pootzko** [comment]
Thanks! I'll make the merge and publish during the next couple of days.

**Comment by DJFliX** [comment]
@pootzko subtle poke in case it slipped your mind :). If you're busy no problem.

**Comment by pootzko** [comment]
Hi,

no, you're right. :) It has been 3 almost weeks since your PR. I'll make the new build today in the evening, sorry for the wait.

**Comment by pootzko** [comment]
Hey, to me, your test fails. This is what I get:

```
Test Name:	CreateContinuousQuery_WithResampleStatement_ShouldCreateContinuousQuery
Test FullName:	InfluxData.Net.Integration.InfluxDb.Tests.IntegrationContinuousQueries.CreateContinuousQuery_WithResampleStatement_ShouldCreateContinuousQuery
Test Source:	D:\projects\InfluxData.Net\InfluxData.Net.Tests\Integration\InfluxDb\Tests\IntegrationContinuousQueries.cs : line 60
Test Outcome:	Failed
Test Duration:	0:00:37,666

Result StackTrace:	
at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at InfluxData.Net.InfluxDb.ClientModules.CqClientModule.<CreateContinuousQueryAsync>d__3.MoveNext() in D:\projects\InfluxData.Net\InfluxData.Net.InfluxDb\ClientModules\CqClientModule.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InfluxData.Net.Integration.InfluxDb.Tests.IntegrationContinuousQueries.<CreateContinuousQuery_WithResampleStatement_ShouldCreateContinuousQuery>d__5.MoveNext() in D:\projects\InfluxData.Net\InfluxData.Net.Tests\Integration\InfluxDb\Tests\IntegrationContinuousQueries.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	InfluxData.Net.Common.Infrastructure.InfluxDataApiException : InfluxData API responded with status code=BadRequest, response={"error":"error parsing query: found RESAMPLE, expected BEGIN at line 1, char 93"}

```

Which version of Influx are you using? I ran this on v0.9.6.

**Comment by DJFliX** [comment]
Hmm... That is probably due to the fact that the Resample statement wasn't present in InfluxDB 0.9.x, I'm using 0.11. I should probably make an effort to add 0.11 mode, but as InfluxData is close to releasing v1.0 of the entire TICK-stack I might as well focus my efforts on the 1.0 beta. 

Would you prefer that I fork this project and fix it for v1.0 or that I attempt to contribute to this library (effectively trying to make it support v1.0 without breaking compatibility with previous versions)?

**Comment by pootzko** [comment]
Alright, I thought so. :)

It has been on my mind that I should implement newer versions as well, but I was a bit lazy since I didn't need it for work. Now that 1.0 is coming out, it's probably a really good time to support that at least. Essentially, everything is mostly ready anyway. All the older versions (of for example parsers, formatters..) only need to inherit from newer ones and just override the breaking changes. The only thing left to figure out is how to setup the tests in a smart way so each version could be tested and it should be an easy ride from there. 

I will have quite a bit of free time in the following two weeks so I'll play with it. If you want to help, you're more than welcome. Perhaps just make it a new feature with git flow, if it's not a problem? If it's easier for you, and if you want it, I could give you contributor access to the repo.

**Comment by DJFliX** [comment]
Sounds great! Indeed testing for older versions is kind of a pain,  but on the other hand, no features are added to 0.9 so no improvements are needed. As most of the versions before the latest release aren't even installable focussing on not explicitly breaking 0.9.x and supporting 1.0 sounds sensible. 

I do work with git flow, so that's no problem at all. Do you have a list of things in 1.0 that need to be implemented (do you even want to build such a list?) or would you rather use add/fix features as we go?

Regards,

**Comment by pootzko** [comment]
We could make a list, it could be useful. 

In the future if someone really requires something specific for a specific (older) version, it could possibly be added, and the 0.9 lib in general I think should work with newer influx versions where API's didn't change.

I think we should first make sure everything we have in 0.9 works for 1.0, and after that start adding new stuff in. Two things I would like to take care of are [#8](https://github.com/pootzko/InfluxData.Net/issues/8) and [batching support](https://github.com/pootzko/InfluxData.Net/issues/5), other than that, I don't know, maybe add support for more API stuff, some real unit tests (instead of these "integration" ones) and whatever else. If you have any ideas, feel free to add them.

**Comment by pootzko** [comment]
I managed to abstract away the tests to support multi-versioning. It was a bit tricky but works nicely now. I'll fix the remaining 4 InfluxDB test tomorrow and then see what's up with the Kapacitor tests and fix that as well. So hopefully I'll deploy all this in the next few days.

**Pull request merged**
