### PR TITLE
Fix to DiagnosticsParser.GetDiagnosticsSystem() to handle times as String or DateTime

### PR DESCRIPTION
**Pull request by meverett**
Added a fix to DiagnosticsParser.GetDiagnosticsSystem() to handle diagnostic system times as either String or DateTime.

Also added an UptimeTimeSpan property to Diagnostics class and added a Go duration string parser to DiagnosticsParser.GetDiagnosticsSystem() to parse the duration string as a TimeSpan in addition to the raw Go Uptime string.

### CODE REVIEW

**Comment by pootzko** [comment]
All tests pass. Job well done. Thanks.

**Comment by pootzko** [comment]
Just one question here, I see you handled h/m/s. I can't find it right now, but should this also parse d as in days? Or would it return hours (for example 25h for 1d1h)? Do you know perhaps?

**Comment by meverett** [comment]
You know I suppose the days could be added for good measure. In theory it's as simple as just adding another conditional that works as the others do and I already sort of provisioned for that.

The reason that I did not include day was that in the Go documentation for [duration](https://golang.org/pkg/time/#Duration) it indicated that the only valid time units where: ns, us/µs, ms, s, m, h. Since the uptime string returned is just a [duration.String()](https://github.com/influxdata/influxdb/blob/07071279dc550ce7ed7fbd151b7d7385d00ee4c2/monitor/system.go#L24) I assumed it would never deliver a time unit that was not defined in the spec. Also if you check out the documentation for the [ParseDuration](https://golang.org/pkg/time/#ParseDuration) function which parses a duration from a string, they also state valid values are: ns, us/µs, ms, s, m, h.

We could put it in to future proof things. Or I guess another option would be to get the uptime string from an InfluxDB server that's been up and running for days and verify. But based on my research into the documentation above I felt comfortable leaving it out as there was no indication it would ever be a unit that would return from a duration string.

**Comment by pootzko** [comment]
I let my test VM run overnight and I'll be able to check this today in the evening. :D I'll let you know.

**Comment by pootzko** [comment]
Just checked this out. It returns >24h format. For example this is what I'm getting atm: "37h10m58.614706299s". So I guess they're consistent and we don't have to parse days as well. For now at least.

**Comment by meverett** [comment]
Awesome :)

**Pull request merged**
