### PR TITLE
Implemented support for dotnet-core, without breaking backwards compatibility

### PR DESCRIPTION
**Pull request by hanssens**
This PR is a spontaneous effort to migrate the InfluxData project to dotnet core. 

### In short, what has been done

* Converted project files to dotnet core (LTS)
* Re-added most dependencies to dotnet core compliant variants
* In test project, refactored ConfigurationManager to a dotnet core compatible implementation
* In test proejct, removed dependency on AutoFixture

Which results in:

* It builds and compiles properly
* Historic commits remain intact
* Backwards compatible with .NET 4.5+
* No code changes in the projects (other than the test project)

### Note: requires work on one remaining issue

There is one issue remaining: most integration tests fail. This is because the `_fixture.MockAndWritePoints` operation doesn't generate the correct amount of expected (unique) measurements. I am assuming this worked before. If so, this might be related to my poor man's workaround for AutoFixture in the `MockPoints()` operation. 

Fixing the tests on this part **requires a second opinion** to see what I've missed there (/cc @pootzko).

Other than that, this should be ready to go for a broader test. Hope you like it...

### CODE REVIEW

**Comment by hanssens** [comment]
An additional note: another remaining work item would be to update the NuGet package (in the project.json as well as the NuGet spec).

**Comment by pootzko** [comment]
Hey @hanssens,

sorry for not replying earlier, I've been quite busy. Thanks for the PR. As soon as I have enough time I'll take a look into this.

**Comment by pootzko** [comment]
Hi,

sorry for the really long delay.. I don't really do much Influx-related work at my job any more except maintain what we already have in place, or when I merge the few fixes and improvements that others send every now and then. And this is kind of a large-ish PR (it requires some time to figure out the changes that have been made, how they fit together, how to properly make the nuget package now etc..) and that's why I didn't give it enough attention so far. On the other hand, I really appreciate the work and especially since it seems like a lot of effort has gone into it.

That being said, I wouldn't like to see this effort go to waste, but it seems like I would need to spend quite a bit of time to get a grasp of all the changes (maybe I'm wrong about this, your feedback would be valuable) and it's kinda hard for me to justify spending so much time on this as I have other things which require my attention and have a higher priority for me personally.

So, I was wondering if you're still interested in helping out with this net-core support? I merged your branch into the [net-core branch](https://github.com/pootzko/InfluxData.Net/tree/feature/net-core) and I actually had only a single conflict (I expected more since some improvements were added since you made the PR) which was easy to resolve. But when I tried to open the solution in VS2017 and it kind of blew up (VS wanted to convert all the projects to xproj's, and after I said "ok, fine" - it complained about not being able to even build "because System.Net.Http"). I tried to do the same with your `dotnet-core-upgrade` branch. I checked it out, and tried to open the SLN in VS2017 and had the exact same scenario. So that's when I decided to give you a shout here. :D 

My questions/cry-for-help would be - which VS did you use when you were doing this? I assume VS2015? I know a lot of libs actually waited for the .net standard 2.0 to come out to start providing support for .net core. And as far as I know that did come out. Do you feel that it's all stable enough (both VS support and the standard and .net core itself)? How much do you know about VS support for these things (I know the shifted between csproj, xproj and if I remember correctly something else as well a few times and they weren't able to decide what to go with in the end). Would you be willing to help in making this work with VS2017? Or should it work without problems with 2015? And do you perhaps know what's the standard workflow for .netcore nuget support? Would this have to be a separate nuget, or could it be build in a way which would support everything (as far as I understand, that's what the .net standard is for)? Sorry for the newbish questions, I haven't started using .net core yet and haven't researched it in such detail yet so I have plenty of questions.

So, perhaps you could provide some help/feedback  with this whole .netcore business if you're still interested/have_time/will. :) If you're interested, I can add you to the repo. If not, perhaps let me know as well.

In any case - looking forward to your reply! And thanks. :)

**Comment by hanssens** [comment]
@pootzko Thanks for taking the time to look into it! 

Indeed, the original PR was created with dotnet core 1.0, in VS2015. It would now be better to update this to dotnet core 1.1, with VS2017 tooling. 

Pros would be:

* Backwards compatibility shouldn't be a problem if we target both netstandard *AND* .NET 4.6+, for example. 
* Migration to dotnet core 2.x later on this year should be a breeze

Cons would be:

* Breaking change where developers of the library are required to code in recent IDE's, like Visual Studio 2017 (or [Visual Studio Code](https://code.visualstudio.com/), or [JetBrains Rider](https://www.jetbrains.com/rider/))

---

With that in mind, I've been working on some internal projects with these changes already. And ItJustWorks™ with new dotnet core apps as well as older .NET 4.6+ projects. 

And I'd be more than happy to invest some time in it to update the PR (or `net-core` branch), but I'd love it to be merged and pushed to NuGet on a relatively short notice. Is that something we can work on?

**Comment by pootzko** [comment]
Great! Yes, sounds good. How short do you need it to be?

I don't think having to upgrade your IDE would be of any issue since VS2017 community edition is free. So it's just the matter of having to install it. And there isn't really many people doing the development. And I believe no one is doing any active development (as far as I know). 

Ok, I'll add you to the repo and you'll be free to write to all branches except master. You can then continue on the feature/net-core branch of this repo and later it will get merged into dev and then into master (I'm following the git-flow pattern). Regarding the tests that you mentioned in your original message, I'll look into that bit once you think it's all ready. We can then deploy the nuget.

If it turns out we need to communicate a lot to coordinate this, we can do it over skype/gtalk/slack/whatever if you want.

Thanks!

**Comment by hanssens** [comment]
Awesome, thanks. I'll work on it the coming time. For direct communication, perhaps you can setup a [Gitter channel](https://gitter.im/) specifically for this repo?

**Comment by pootzko** [comment]
Sure, I'll do that tonight. Cheers!

**Pull request closed without merging**
