### PR TITLE
template support

### PR DESCRIPTION
**Pull request by ormocha**
New:
-	Create BaseTaskParams
-	Create TemplateTaskParams
-	Tests for creating task with template

Changes:
-	ITaskClientModule DefineTaskParams now gets BaseTaskParams as argument
-	TaskClientModule_v_0_10_1 thorws unsopported exception for TemplateTaskParams
-	TaskClientModule uses ToJsonDictionary to create the task from BaseTaskParams
-	BodyParams now contains TemplateId and TemplateVars for template-support

connected to issue #18

### CODE REVIEW

**Comment by ormocha** [comment]
Hey @pootzko,
Have you had the chance to check this PR?

**Comment by pootzko** [comment]
Hey,

sorry for not merging it in yet. I just took a quick glance and generally it seems ok but  I will have to move the mapping logic back from the model class into the clientModule class because these models are simply transfer objects and should not contain this kind of logic as then it becomes untestable in the long run. 

Also, by changing the DefineTaskAsync signature the API got slightly broken and at that state is not backwards compatible which I would like to avoid. This should be an additional overload rather than a fully replaced API method. And if the old one looks like it will be obsolete then the obsolete attribute should be added instead (until the next major version of the lib).

**Comment by ormocha** [comment]
Hi,
Thanks for the reply, add any changes you think are needed.
about the slightly broken API, it has backward compatibility, only the signature is changed.
here if you need any help :)

**Comment by pootzko** [comment]
No worries man, great work. I'm really glad you helped, thank you for that. :)

**Comment by pootzko** [comment]
Hi, you changes are now live as part of [v5.0.6](https://www.nuget.org/packages/InfluxData.Net/5.0.6). Thanks once more for the contribution. Cheers.

**Comment by pootzko** [comment]
Sorry, I unlisted it (you can still access it and use it if you wish with this direct link). I have some issues with resolving the version of Newtonsoft.JSON nuget dependency. With InfluxData.Net v5.0.6 the Newtonsoft.JSON v9.0.1 is enforced and I need to fix this first before publishing the package.

**Pull request merged**
