### PR TITLE
Multi Query null check

### PR DESCRIPTION
**Pull request by Nicholi**
Needs the same null series check as single query method.

I know it looks like you LITERALLY just implemented this, but needed to use immediately anyways.

### CODE REVIEW

**Comment by pootzko** [comment]
Hi, thanks for the PR. 

I however in the mean time changed the method to this (not pushed yet):

```cs
public async Task<IList<IList<Serie>>> QueryAsync(string dbName, string[] queries)
{
    var response = await this.RequestClient.Query(dbName, queries.ToSemicolonSpaceSeparatedString());
    var queryResult = response.ReadAs<QueryResponse>();
    var seriesList = new List<IList<Serie>>();

    Validate.NotNull(queryResult, "queryResult");
    Validate.NotNull(queryResult.Results, "queryResult.Results");

    // Apparently a 200 OK can return an error in the results
    // https://github.com/influxdb/influxdb/pull/1813
    foreach (var result in queryResult.Results)
    {
        if (result.Error != null)
        {
            throw new InfluxDbApiException(HttpStatusCode.BadRequest, result.Error);
        }

        seriesList.Add(result.Series.ToList());
    }

    return seriesList;
}
```

Which actually makes sense because if you executed multiple queries at once, you would actually expect to get grouped results (grouped serie lists) instead of a flat serie list. 

I might however add an additional overload that would return a flat result (basically method that you're currently using, which you fixed). Just not sure what to name this method.

What do you think?

**Comment by Nicholi** [comment]
I suppose that would be good if the caller of QueryAsync explicitly needed to have the number of series match the number of queries. You would essentially be adding a null item to the list, which was what was throwing an exception before AddRange(null).

Seems like a mad idea to just add the null item to the list, as this would require the caller to always check first if any items are null in the list before even pulling data from the series.

In my opinion the caller would probably prefer a list of non-null objects, and they can use the Serie.Name to identify which of their queries produced results and if something is not found in the list, that means it didn't.

**Comment by pootzko** [comment]
The thing is - I would like to be consistent to what InfluxDB returns in this case, and if you execute multiple queries at once - you will get multiple _results_ where each of them can contain multiple _series_ inside.

I would of course do the null check and return an empty serie list if the result didn't return any series.

That would then be the default way of multiQuery, and the other method would return a flattened list.

**Comment by pootzko** [comment]
Ok, so I kept the same signature for `QueryAsync` for multiple queries and added an additional method called `MultiQueryAsync` which does the thing I described. Thanks for the contribution. :)

**Comment by Nicholi** [comment]
Ahh I was tired and wasn't fully understanding what you were trying to get to. Totally makes sense now, as the normal single query was flattening the results and since there should be only 1 result that totally makes sense, and was semi-useful to the caller (as the "result" contains no additional data currently, just series). You may want to remove the method flattening the list in that case, as it's not strictly necessary and the caller can easily flatten the model themselves. Also may be semi-confusing to someone not understanding that the ONLY difference between those two (currently) is that they are flattening the list of series.

So yeah IEnumerable<IEnumerable<Serie>> may look funny but from a design perspective it is mirroring influxdb, so I agree. It may prove useful in the future if the "results" gain additional properties to identify themselves other than just the series information.

**Pull request merged**
